### ISSUE TITLE
MiniProject Analysis Discussion 

### ISSUE THREAD

**Issue by hackmasterheather** [bereket1197/MiniProject1#1]
For the mini project, I plan to analyze works from Charles Dickens and Ernest Hemingway. For comparisons of two works by the same author I will be comparing Charles Dickens's "Bleak House" and "A Christmas Carol". For a comparison of works by two different authors, I plan to compare "Bleak House" to Robert Frost's "The Sun Also Rises". I will be comparing the word frequencies of these works. As time permits, potentially sentiment.

**Comment by bereket1197** [comment]
I think this is a great idea. I love "A Christmas Carol" and from what I have read about "Bleak House" I think both have similar tones. It will be interesting to see if there is a pattern with language since most of Dickens' work will end up having the main character realize some major learning curve which conveys to the reader whatever his central theme is. I have never read "The Sun Also Rises" but again based on some of the reviews it seems like it is similar enough to also be good reference to compare to Dickens.
